version: '3.5'
slug: cups
name: CUPS
description: Open source printing system used on Linux and other operating systems.
url: https://hub.docker.com/r/chuckcharlie/cups-avahi-airprint
image: chuckcharlie/cups-avahi-airprint
arch:
  - aarch64
  - amd64
webui: http://[HOST]:[PORT:631]

map:
  - type: addon_config
    read_only: false

host_network: true

ports:
  631/tcp: 631
ports_description:
  631/tcp: CUPS

init: false
